# Generated by Django 3.2.6 on 2021-08-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='email',
        ),
    ]
