# Generated by Django 3.2.6 on 2021-08-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_auto_20210819_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='Username'),
        ),
    ]
