# Generated by Django 3.2.6 on 2021-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='address',
            field=models.CharField(default=None, max_length=256, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.CharField(default=None, max_length=200, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
